version: "3.9"
services:
    web:
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            PORT: "4100"
            MIGRATE: "true"
            NODE_ENV: "production"
            SECRET_KEY: "my_super_secret_key"
            MONGODB_URI: "mongodb://admin:password@mongodb:27017/"
        ports:
            - "8888:4100"
        depends_on:
            - "mongodb"

    mongodb:
        image: mongo:4.4.10-rc0
        command: mongod --quiet --logpath /dev/null
        ports:
            - "27017:27017"
        volumes:
            - mongo:/data/db
        environment:
            - MONGO_INITDB_ROOT_USERNAME=admin
            - MONGO_INITDB_ROOT_PASSWORD=password

volumes:
    mongo:
#docker-compose up
#docker-compose stop
#docker-compose down --volumes
